### ISSUE TITLE
Stream order to river network extraction

### ISSUE THREAD

**Issue by jorgianepires1** [mdbartos/pysheds#100]
Good morning, have you already implemented stream order to river network extraction? If yes, which method have you choose to impĺement?
Congratulations, pysheds is very helpful!

**Comment by mdbartos** [comment]
Hi. If there is a particular one you'd like implemented, let me know. Also, feel free to submit a pull request if you've written one. Thanks.

**Comment by mdbartos** [comment]
Strahler stream order was added in pysheds v0.3. Please reopen an issue if another stream order algorithm is desired.
