### ISSUE TITLE
extract_river_network IndexError 

### ISSUE THREAD

**Issue by jaimebayes** [mdbartos/pysheds#107]
hi,

I am getting this index error, but i cant figure it out how to fix it.
No problem with 'catch' or 'acc'.
Any suggestion?

Thanks in advance, JL

`branches = grid.extract_river_network('catch', 'acc')`

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-18-ef316ad79610> in <module>()
----> 1 branches = grid.extract_river_network('dem', 'acc')

2 frames
/usr/local/lib/python3.6/dist-packages/scipy/sparse/lil.py in _set_intXint(self, row, col, x)
    302     def _set_intXint(self, row, col, x):
    303         _csparsetools.lil_insert(self.shape[0], self.shape[1], self.rows,
--> 304                                  self.data, row, col, x)
    305 
    306     def _set_arrayXarray(self, row, col, x):
_csparsetools.pyx in scipy.sparse._csparsetools.lil_insert()
_csparsetools.pyx in scipy.sparse._csparsetools.lil_insert()
IndexError: column index (1014559) out of bounds

**Comment by mdbartos** [comment]
The error seems to be coming from line 2747, when constructing the sparse adjacency matrix. It's somewhat hard to diagnose without having access to the data.

I may rewrite `grid.extract_river_network` to be more like `grid.extract_profiles`, as the code is a lot easier to understand. It may be worth trying to see if `grid.extract_profiles` works with your data.

**Comment by jaimebayes** [comment]
Thanks for your answer, but when I try to use grid.extract_profiles, it requires a mask (boolean array) indicating channelized regions. I suppose these regions comes from grid.extract_river_network or where i can get it from.

`profs = grid.extract_profiles('dir', dirmap=dirmap, nodata_in=None, routing='d8')`

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-39-b5e421fc16d6> in <module>()
      1 
----> 2 profs = grid.extract_profiles('dir', dirmap=dirmap, nodata_in=None, routing='d8')

TypeError: extract_profiles() missing 1 required positional argument: 'mask'

**Comment by mdbartos** [comment]
Greetings,

For the mask, you can just use a threshold value on the accumulation. So for example:

```python
profs = grid.extract_profiles('dir', mask=grid.acc > 100, dirmap=dirmap, nodata_in=None, routing='d8')
```

I will try to take a look at this problem later this week. Let me know if it's possible to give me some of the data that triggers this error.

**Comment by jaimebayes** [comment]
Hi,

It was my bad, the problem comes from the fact that when I cut my dem to small area, i didnt calculate all function for this new area, so when I try to extract river networks, data sizes didnt match.
Thanks so much for your help, i was wondering where was the fault. Finally i got it.
Now, I have my river network and it looks really fine.

Best regards, JL
