### ISSUE TITLE
grid.to_raster - TypeError: invalid dtype: 'int64'

### ISSUE THREAD

**Issue by bhanu-IITD** [mdbartos/pysheds#109]
Hey Matt,
I am trying to export the generated flow direction and accumulation grids using `grid.to_raster` but getting an error : `TypeError: invalid dtype: 'int64'`. Please suggest the solution.

Thanks.
Bhanu
![image](https://user-images.githubusercontent.com/60338532/78178035-a74f9a00-747c-11ea-9e0c-e6e03b6b6b75.png)

**Comment by mdbartos** [comment]
Greetings,

I believe for integer datatypes rasterio only supports int8, int16, int32 and uint8, uint16, uint32.

You can pass the desired dtype as an argument to `to_raster` (e.g. to_raster(..., dtype=np.int32)).

Let me know if that helps.

Thanks,
MDB

**Comment by bhanu-IITD** [comment]
Hi Matt,
Thanks for the help. I have implemented a solution as shown in the screenshot. It might not be the best workaround but it works.
Thank you.
![image](https://user-images.githubusercontent.com/60338532/78222322-ad786180-74e2-11ea-8852-e5da508af485.png)
