### ISSUE TITLE
How to cite pysheds?

### ISSUE THREAD

**Issue by itati01** [mdbartos/pysheds#120]
Hi Matt,

How should / can I cite pysheds?

Thank you in advance

**Comment by mdbartos** [comment]
Greetings,

I can create a Zenodo DOI if that would be helpful.

Hoping to write a paper on it eventually.

Thanks,
MDB

**Comment by mdbartos** [comment]
Greetings,

I've created a zenodo record here:
https://zenodo.org/record/3822503

The master DOI for all versions is: `10.5281/zenodo.3822494`

Zenodo automatically lists all contributors as authors---github handles are used when real names are unavailable. This may not be the most appropriate option for a journal citation. In that case, I'd recommend using something like:

```
@misc{bartos_2020,
    title  = {pysheds: simple and fast watershed delineation in python},
    author = {Bartos, Matt},
    url    = {https://github.com/mdbartos/pysheds},
    year   = {2020},
    doi    = {10.5281/zenodo.3822494}
}
```

Thanks again for your interest and contributions!
MDB

**Comment by itati01** [comment]
Thanks a lot for the quick help! Unfortunately, I still have no time for further contributions. Hopefully, this will change one day.
