### ISSUE TITLE
Accumulation output array of 1's

### ISSUE THREAD

**Issue by joeshuttleworth** [mdbartos/pysheds#131]
When I am trying to run the grid.accumilation step I end up with an array of only 1's.

Raster([[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]])

flowdir runs fine in the previous step. 

Is this a known issue/ is there something obvious I am doing wrong?

**Comment by joeshuttleworth** [comment]
Ignore me... problem solved

**Comment by deeptimahesh** [comment]
@joeshuttleworth Hey! Can you tell me how exactly you solved this? I'm running into the same output as well and my catchment is an array of 0s.

**Comment by bmalbusca** [comment]
Hi @deeptimahesh  See issue [113](https://github.com/mdbartos/pysheds/issues/113) and  and issue [92](https://github.com/mdbartos/pysheds/issues/92)
