### ISSUE TITLE
RFSM for a point source

### ISSUE THREAD

**Issue by joeshuttleworth** [mdbartos/pysheds#136]
Hi - does anyone know if it is possible to run RFSM flooding for a point source as opposed to a uniform distribution of water? 

Thanks

**Comment by mdbartos** [comment]
Greetings,

You should be able to specify a point source using an appropriately-defined `input_vol` array as shown here:
https://github.com/mdbartos/pysheds/blob/master/examples/rfsm.ipynb

The example uses a uniform water distribution by using `np.ones` to define the array (i.e. water at every pixel). But you can specify a custom array to input water at any subset of pixels you'd like.

Thanks,
MDB
