### ISSUE TITLE
is it possible to delineate subbasins by using pour point

### ISSUE THREAD

**Issue by lj512lj512** [mdbartos/pysheds#138]
I have a large research area and I have some hydrological stations unevenly distributed in the basin. I want to get the subbasin of my research region and make the hydrological stations as pour points for each subbasin, is it possible to use pysheds to do this. I can use ArcGIS to do this with the following command:

1. input raw DEM
2. fill
3. flow direction
4. accumulation
5. snap pour point
6. watersheds

**Comment by mdbartos** [comment]
Yes, this process is outlined in the tutorial included in the README.
