### ISSUE TITLE
Accumulation weights not calculating correctly if input weights type is int

### ISSUE THREAD

**Issue by ar-siddiqui** [mdbartos/pysheds#149]
I have a direction grid and a weight grid.

When I run accumulation, it does not create correct results if I do not convert the weight grid to float 32 explicitly in line 2 of the following code.

```python
weights = Grid.from_raster(r'C:\Users\asiddiqui\Documents\Projects\NSPECT\HI_SAMPLE_TEST_DATA\original\pysheds\HSG.tif', data_name='soil', nodata = 255)
grid.accumulation(data='dir', weights=weights.soil.astype(np.float32), out_name='acc')
grid.to_raster('acc', r'C:\Users\asiddiqui\Documents\Projects\NSPECT\HI_SAMPLE_TEST_DATA\original\pysheds\acc.tif', dtype=np.float32)
```

Both datasets are attached.

[HSG.zip](https://github.com/mdbartos/pysheds/files/7245614/HSG.zip)

**Comment by mdbartos** [comment]
Greetings,

I just pushed a major update that---among other things---handles types more explicitly. I'd highly recommend upgrading to pysheds v0.3 and seeing if the problem is fixed.

**Comment by mdbartos** [comment]
Please reopen an issue if the problem persists.
