### ISSUE TITLE
Quantifying the amount of water upstream

### ISSUE THREAD

**Issue by BrandonKMLee** [mdbartos/pysheds#150]
There is a blog recently that altitude and watersheds are related to obesity (due to water pollution).
- https://slimemoldtimemold.com/2021/07/07/a-chemical-hunger-part-i-mysteries/
- https://slimemoldtimemold.com/2021/07/11/a-chemical-hunger-part-ii-current-theories-of-obesity-are-inadequate/

Since using pure altitude alone is not useful in quantifying the amount of water a place has been affected, is there a good metric based on geography to determine who much water is upsteam?

Example metric: Area of watershed - Distance from the end of the stream to the location in question * the "width" of the watershed
- As the watershed gets larger (and as the "width" increases), the amount of water upstream should increase
- As the distance to the end of the steam reaches zero, the amount of water upstream becomes equivalent to the area of the watershed

**Comment by mdbartos** [comment]
Greetings, 

Interesting, I saw that article as well.

What you're interested in is some (possibly weighted) version of the `grid.accumulation` function.

**Comment by mdbartos** [comment]
Please reopen an issue if you have more questions.

**Comment by BrandonKMLee** [comment]
@mdbartos thank you for the reply, this will come in really handy in handling related issues.
