### ISSUE TITLE
installed pysheds 0.3 with pip after runtime error with setup.py

### ISSUE THREAD

**Issue by itati01** [mdbartos/pysheds#169]
Hi,
I tried to install ```pysheds 0.3``` from Github following the readme, i.e. with ```python setup.py install```.

After the installation, ```from pysheds.grid import Grid``` resulted in a ```RuntimeError: cannot cache function '_d8_flowdir_numba': no locator available for file 'C:\\Users\\xxx\\Anaconda3\\lib\\site-packages\\pysheds-0.3-py3.8.egg\\pysheds\\_sgrid.py'````. I am not sure whether this is related to this [numba issue](https://github.com/numba/numba/issues/4908).

I use Anaconda under Windows. After installing the missing libraries with ```conda``` and running ```pip install .```, everything is working.

Cheers

**Comment by mdbartos** [comment]
Interesting. I was able to install on my windows laptop just using conda:

```
conda create -n pysheds-env python=3.9
conda activate pysheds-env
conda install pysheds
```

**Comment by mdbartos** [comment]
Please reopen if the issue persists.
