### ISSUE TITLE
Shape and extent of watershed is not correct in some cases, just moving 2 meters away as per issue #126

### ISSUE THREAD

**Issue by iamaxy81** [mdbartos/pysheds#185]
I have encountered the same behaviour as per issue #126. I have wrong watershed calculated for some pour points located on the streamline, but if I move just a few meters, also away from the stremline, I have the correct result. I tried setting snap='center' in the catchment calculation but nothing changed: 
grid.catchment(data='dir', x=x, y=y, out_name='catch', recursionlimit=15000, xytype='label', snap='center')

As you can see in the attached images two points that are both on the streamline, and less then half a meter far from each other, produce different results.

![image](https://user-images.githubusercontent.com/86362816/155681904-e2b77164-ac00-4cb8-92c1-e0082d536e27.png)
![image](https://user-images.githubusercontent.com/86362816/155681990-ebdec9f2-7807-413c-a138-c03efec65b0f.png)

**Comment by mdbartos** [comment]
Have you tried using `grid.snap_to_mask` to snap your coordinate to a high-accumulation cell?

**Comment by iamaxy81** [comment]
Thanks man! It works
