### ISSUE TITLE
Set the threshold of the catchment area?

### ISSUE THREAD

**Issue by staceyzhang-cbcl** [mdbartos/pysheds#225]
I wonder if there is an option to set the area threshold of the catchment? 

I am working on delineating catchments/subcatchments of a large region. With a list of outlets along a river, the catchments delineated become larger as the outlets approach the main channel.  

For example, the target catchments look like this. This was created using pcswmm's watershed delineation tool by setting a certain level of target discretization.
![image](https://github.com/mdbartos/pysheds/assets/137422045/11e1dfeb-d4f7-4dce-af39-ae95e8b70f68) 

But when I set the same pour point, the area is rather large.
![image](https://github.com/mdbartos/pysheds/assets/137422045/8ac0f87f-eec2-410d-bffb-9dc54d1d9303)

**Comment by mdbartos** [comment]
It is possible to limit the catchment size. One could add a counter to this function that checks for the number of total cells added:

https://github.com/mdbartos/pysheds/blob/32fb2efba94c5da4ee8e2556d484a218d352226b/pysheds/_sgrid.py#L316

Is that what you want to do though? How is the target level of discretization defined?

**Comment by staceyzhang-cbcl** [comment]
I took a look at the function, but not sure where to add the counter and when do use it. Is it before `grid.catchment`? But it does seem like what I want to do. 

The catchment discretization seems to have something to do with the landscape heterogeneity, and therefore generates distributes output variables ([Dehotin and Braud, 2008](https://hess.copernicus.org/articles/12/769/2008/hess-12-769-2008.pdf)). What I was told is that this could limit the size of catchments to be delineated. So I think this function might be what I'm looking for. How do I use it?

**Comment by staceyzhang-cbcl** [comment]
Hi! 

It turned out that I wasn't using the right way to put together the polygons into one shapefile. I should have sorted the polygons in a descending order, so that smaller polygons wouldn't be covered by larger ones. Thank you Matt for answering my question!

![image](https://github.com/mdbartos/pysheds/assets/137422045/c72269e7-23dc-48b0-b450-00b8024621ad)

**Comment by mdbartos** [comment]
Thanks. If you want to create non-overlapping polygons, there is a code example in [this issue](https://github.com/mdbartos/pysheds/issues/64#issuecomment-462951248).
