### ISSUE TITLE
TypeError: affine transformation matrix required

### ISSUE THREAD

**Issue by msaharia** [mdbartos/pysheds#23]
1.  Dowloaded and unzipped this file: 
http://earlywarning.usgs.gov/hydrodata/sa_con_3s_grid/CA/n30w100_con_grid.zip

2. `grid = Grid.from_raster('n30w100_con_grid/n30w100_con/n30w100_con/', data_name='dem')`

3. Error: `TypeError: affine transformation matrix required`

**Comment by mdbartos** [comment]
Interesting ... the same line works on my machine. 

Which version of rasterio are you using?

**Comment by msaharia** [comment]
Here

Name: rasterio
Version: 0.36.0

**Comment by mdbartos** [comment]
Ah. Only versions >1.0 of rasterio are supported due to some breaking changes that happened with the 1.0 release: https://github.com/mdbartos/pysheds/issues/13

The version requirement should be specified in the current `requirements.txt`

**Comment by msaharia** [comment]
Thanks! I'll update.
