### ISSUE TITLE
Allow user to disable `parallel=True` with numba

### ISSUE THREAD

**Issue by fmaussion** [mdbartos/pysheds#234]
We, at https://github.com/OGGM/oggm, are using pysheds successfully to do useful stuff for glacier modelling - so thanks a lot for this great tool!

I'd like to be able to disable the use of parallelism in numba, which essentially involves replacing True to False in a [few calls to numba](https://github.com/search?q=repo%3Amdbartos%2Fpysheds%20parallel%3DTrue&type=code).

The reason I need this is that we are calling pysheds on a large (>200k) number of small glacier domains and we are doing our own multiprocessing. We've found that numba then creates concurring processes and everything take forever (order of magnitudes more than when disabling multiprocessing in numba).

I don't know the codebase well enough to suggest the best way to do this cleanly within pysheds. Does pyshed have global variables, or run parameters? Or should we go by keywords in the whole API? 

Thanks!

**Comment by groutr** [comment]
https://numba.readthedocs.io/en/stable/reference/envvars.html#envvar-NUMBA_NUM_THREADS

You can set the number of threads that numba uses with an environment variable. In your case, you would want to set `NUMBA_NUM_THREADS=1`

**Comment by fmaussion** [comment]
Thanks very much! That solves it very elegantly 👍
