### ISSUE TITLE
Save watershed polygon to shapefile

### ISSUE THREAD

**Issue by xtcai** [mdbartos/pysheds#27]
I found pysheds very useful for me. Thank you for sharing it on Github.
The examples are great in showing how to perform a variety of watershed processing and save the results as figures. However, showing how to save them into raster and vector files is also important. For example, after delineating a watershed, how can I save the polygon to a shapefile?

**Comment by mdbartos** [comment]
Greetings,

I've added a notebook under `recipes` that shows how to save the catchment polygon to a shapefile:
https://github.com/mdbartos/pysheds/blob/master/recipes/write_shapefile.ipynb

I can also add an example showing how to write the river network to a shapefile.

Let me know if that helps.

Thanks,
MDB

**Comment by xtcai** [comment]
Thank you very much. It really helps! This is exactly what I need for now. But adding further examples would certainly help for other users.
Thank you again for your efforts.

**Comment by mdbartos** [comment]
I've added another example to the notebook showing how to write an extracted river network (geojson) to a shapefile:

https://github.com/mdbartos/pysheds/blob/master/recipes/write_shapefile.ipynb
