### ISSUE TITLE
Support GeoTIFF?

### ISSUE THREAD

**Issue by lz80521** [mdbartos/pysheds#30]
I was wondering how I could use this with tif files. Should I convert them to ESRI GRID format first or is there any workaround for this? Thank you!

**Comment by mdbartos** [comment]
Rasterio supports geotiff, which means that they should be supported: https://rasterio.readthedocs.io/en/latest/

Did you try using `grid.read_raster` or `grid.from_raster` on your geotiff? It seems to work for me.

**Comment by mdbartos** [comment]
@lz80521: Were you able to resolve this problem?

**Comment by ShashankBice** [comment]
Hi @mdbartos ! What if I do not have grid defined from beforehand and want to read the tiff file and define the grid file based on the properties of the tiff file?
Is there a way to define the grid geospatial properties manually?
Please let me know..
I tried grid = Grid(['affine=dataset.transform','shape=(219,564)','nodata=-1.79769313486231571e+308','crs=dataset.crs'])
but it fails!
Please let me know.....

**Comment by mdbartos** [comment]
Greetings,

If you call:

```python
grid = Grid.from_raster('/path/to/file.tiff', 'dataset_name')
```

It should populate the affine transform, shape, and other metadata of `grid` automatically.

Alternatively, `read_raster` will populate the metadata if it is the first dataset in the grid:

```python
grid = Grid()
grid.read_raster('/path/to/file.tiff', 'dataset_name')
```

These are probably the most preferred ways of doing it.

If you need to set attributes manually, you can also do so after instantiating a grid:

```
grid.affine = dataset.transform
grid.shape = dataset.shape
grid.crs = dataset.crs
grid.nodata = -1.79769313486231571e+308
```

There are some other ways that may be easier or harder depending on your situation, but see if any of those help.

**Comment by ShashankBice** [comment]
Hi @mdbartos !
Thanks for the quick reply. After going through other issues with pysheds, I found the problem to be in version of rasterio. I use anaconda's rasterio and the latest release on anaconda does not play well with gdal. I did a pip install of rasterio and it works. And thankfully, it does not messes my other gdal related packages :)
Thanks for the help, I think I can now get my assignment done tomorrow morning!

**Comment by mdbartos** [comment]
lol, no problem

**Comment by mdbartos** [comment]
To plot, it just call:
```python
from matplotlib import pyplot as plt

plt.imshow(grid.view('dem'))
```
This was omitted in the readme for brevity, but can be seen in the quickstart:
https://github.com/mdbartos/pysheds/blob/master/examples/quickstart.ipynb

`grid.view` returns a Raster object (essentially an ndarray with metadata) that represents a "view" of the data at the current affine transform, shape, crs, and nodata value.

**Comment by bmalbusca** [comment]
issue closed? @mdbartos
