### ISSUE TITLE
Is it possible to get array of streams in the sequence they get filled?

### ISSUE THREAD

**Issue by AtrCheema** [mdbartos/pysheds#39]
Streams are normally filled in order depending upon their relative hight. Many hydrological modeling number streams while creating subbasin files like BASINS etc. How can such an array be obtained in this case?!!!

**Comment by mdbartos** [comment]
Hi Ather,

Do you mean stream order (https://en.wikipedia.org/wiki/Stream_order)?

It's been on my to-do list for a while, but I haven't gotten to it yet. Maybe I can implement it within the next few weeks.

**Comment by AtrCheema** [comment]
Thank you for your response. Yes, I mean similar to stream order. The order calculated by e.g. BASINS is from 1 to max. no. of streams while the Wikipedia shows a bit different.

**Comment by mdbartos** [comment]
Do you have any links showing how BASINS assigns order to the streams? I haven't been able to find any info.

**Comment by AtrCheema** [comment]
Quite a while ago I tried to find it from BASINS src on Github. I couldn't. I will post it here if I find one.

**Comment by mdbartos** [comment]
Strahler stream order has been implemented in pysheds v0.3.
