### ISSUE TITLE
error happened when install in windows 10 64bit 

### ISSUE THREAD

**Issue by DamonsJ** [mdbartos/pysheds#43]
I came across an error when I install pysheds in windows 10 64bit using " pip install pysheds"
here is the errors:

![_20181023162109](https://user-images.githubusercontent.com/28893028/47346484-e1d9d280-d6df-11e8-8e39-448f4a618878.png)

why?
How to fix it?

**Comment by mdbartos** [comment]
It looks like it's failing to install pyproj.

Try the solutions posted here:
https://stackoverflow.com/questions/41724445/python-pip-on-windows-command-cl-exe-failed/41724634

Also see this issue:
https://github.com/jswhit/pyproj/issues/90

Which version of Python are you using?

**Comment by mdbartos** [comment]
You may also want to try cloning pysheds locally, and then running `python setup.py install`

**Comment by DamonsJ** [comment]
Thanks a lot! I think I have solved pyproj problem.
using hint in :
https://stackoverflow.com/questions/41724445/python-pip-on-windows-command-cl-exe-failed/41724634

Open Visual C++ 2017 x86 x64 Cross Build Tools Command Prompt--> change directory cd C:\Users\Test\AppData\Local\Programs\Python\Python36-32\Scripts-->Type: pip install package_name

but rasterio give me a hint that 
![image](https://user-images.githubusercontent.com/28893028/47414060-a2c08580-d7a2-11e8-9614-e171f43c6352.png)

is that to say I have to create a PATH enviroment  named GDAL_CONFIG which include gdal's home path ?

**Comment by mdbartos** [comment]
I think you can either specify path or version. Here's an example with version 2.3.1:
https://github.com/mapbox/rasterio/issues/1467

Rasterio's docs also has some other instructions for installing on Windows: https://rasterio.readthedocs.io/en/latest/installation.html

I don't know if these instructions are compatible with anaconda though.

**Comment by mdbartos** [comment]
Please reopen if the issue persists.
