### ISSUE TITLE
RuntimeError: b'no arguments in initialization list'

### ISSUE THREAD

**Issue by TobiasDK** [mdbartos/pysheds#57]
Hi, I get this error with Windows 10, 64 bit, Anaconda 1.9.6, Spyder 3.3.2, Python 3.7.2, pysheds 0.2.3, pyproj 1.9.5.1. Please advise.
```
from pysheds.grid import Grid
Traceback (most recent call last):

  File "<ipython-input-16-c8708fc12346>", line 1, in <module>
    from pysheds.grid import Grid

  File "C:\ProgramData\Anaconda3\lib\site-packages\pysheds\grid.py", line 33, in <module>
    from pysheds.view import Raster

  File "C:\ProgramData\Anaconda3\lib\site-packages\pysheds\view.py", line 75, in <module>
    class BaseViewFinder():

  File "C:\ProgramData\Anaconda3\lib\site-packages\pysheds\view.py", line 77, in BaseViewFinder
    crs=pyproj.Proj('+init=epsg:4326'), y_coord_ix=0, x_coord_ix=1):

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyproj\__init__.py", line 358, in __new__
    return _proj.Proj.__new__(self, projstring)

  File "_proj.pyx", line 84, in _proj.Proj.__cinit__

RuntimeError: b'no arguments in initialization list'
```

**Comment by mdbartos** [comment]
Looks like pyproj wasn't properly installed, or possibly proj wasn't linked correctly.

You may be missing the actual projection data: https://github.com/jswhit/pyproj/issues/134

I normally use only pip, but I was able to get my pysheds install working on anaconda by first installing all dependencies manually, then installing pip within the anaconda environment, then installing pysheds using pip.

This tutorial also has installation instructions for windows with anaconda: https://www.hatarilabs.com/ih-en/watershed-and-stream-network-delimitation-with-python-and-pysheds-tutorial

I am also currently working on a conda-forge package: https://github.com/conda-forge/staged-recipes/pull/7421

**Comment by kse0202** [comment]
```
import os

os.environ['PROJ_LIB']=r"C://[...path...]/Anaconda3/Library/share" 
```
set your 'proj_list' path
and you could check your proj list in that folder '.../Anaconda3/Library/share'

**Comment by mdbartos** [comment]
Please reopen an issue if the problem persists.
