### ISSUE TITLE
Error in delinate the catchment and grid.to_raster:"blockxsize exceeds raster width"

### ISSUE THREAD

**Issue by hikmet34** [mdbartos/pysheds#60]
Hi @mdbartos,

How do you determine X and Y points?
I tried dozens different points, but i didn'n get true delinate catchment. Besides result of "grid.to_raster" process give error that "blockxsize/blockysize exceeds raster width".

**Comment by mdbartos** [comment]
Greetings,

You can use the `grid.snap_to_mask` method to snap point(s) to the nearest high-accumulation cell. You will need to first compute the accumulation using `grid.accumulation`. See this notebook:
https://github.com/mdbartos/pysheds/blob/master/examples/snap_to_mask.ipynb

The blockxsize and blockysize parameters come from rasterio. They default to 16, which means that in this case, your current output raster is smaller than 16x16 cells. You just need to make sure that these block size arguments are less than the y- and x- dimensions of your output raster.

**Comment by hikmet34** [comment]
Thanks for your reply.
`grid.snap_to_mask` method solved to problem.

I know the blockxsize and blockysize parameters come from rasterio.
This is a view of the catchment data: (7x14)

[[nan nan nan nan nan nan nan nan 43. 37. 33. 34. 38. nan]
 [nan nan nan nan nan 38. 39. 39. 39. 35. 32. 34. 40. 45.]
 [nan nan 45. 40. 38. 37. 36. 36. 33. 32. 31. 33. 40. 44.]
 [nan 50. 49. 45. 40. 37. 34. 33. 31. 30. 31. 33. 38. nan]
 [53. 54. 54. 53. 46. 37. 34. nan nan nan nan nan nan nan]
 [56. 57. 56. 55. 51. nan nan nan nan nan nan nan nan nan]
 [nan 59. 58. nan nan nan nan nan nan nan nan nan nan nan]]

Therefore i fixed to this:
`grid.to_raster(demView,'../Output/clippedElevations.tif',blockxsize=7,blockysize=14)`

But i got error "**ValueError: blockysize exceeds raster height**."

On the other hand i wrote x = 14 and y =7:
`grid.to_raster(demView,'../Output/clippedElevations.tif',blockxsize=14,blockysize=7)`

Result:
"**CPLE_AppDefinedError: _TIFFVSetField:../Output/clippedElevations.tif: Bad value 14 for "TileWidth tag**"

**Comment by mdbartos** [comment]
Try setting them to 2 or 4. The block sizes just need to be strictly smaller than the output dimensions.

**Comment by hikmet34** [comment]
Ok, thanks for all your help

**Comment by vitorrebello** [comment]
Hello @mdbartos,
I have just followed all steps listed above and successfully completed it.
But now I got the following message from grid.to_raster:
**rasterio._err.CPLE_AppDefinedError: MissingRequired:TIFF directory is missing required "StripOffsets" field**
How should I proceed ?
Thanks a lot.
