### ISSUE TITLE
AttributeError: 'Grid' object has no attribute 'detect_nondraining_flats'

### ISSUE THREAD

**Issue by hikmet34** [mdbartos/pysheds#61]
Hi @mdbartos 

I carried out "messy_dem" recipe. 

`depressions = grid.detect_nondraining_flats('dem')`

AttributeError                            Traceback (most recent call last)
<ipython-input-5-f1457889031b> in <module>
      1 # Detect pits
----> 2 depressions = grid.detect_nondraining_flats('dem')

AttributeError: 'Grid' object has no attribute 'detect_nondraining_flats'

**Comment by mdbartos** [comment]
Greetings,

The function was renamed to `grid.detect_depressions` a couple weeks ago. Docs has updated version: https://mdbartos.github.io/pysheds/dem-conditioning.html

I will change the notebook. I will also look into linking the dataset used for that notebook.

Thanks,
MDB

**Comment by hikmet34** [comment]
Okay, thank you. Solved the problem.

Thanks,
Hikmet
