### ISSUE TITLE
Unexpected catchment output

### ISSUE THREAD

**Issue by smnorris** [mdbartos/pysheds#63]
Hi, this seems like a brilliant tool. 

I am testing creating a catchment on a small DEM but not getting the expected result - only a single cell is returned: `Raster([[2]])` The DEM is fine - there is definitely a contributing area higher than the pour point.  My usage seems to be ok too, can you point me to something I might be missing?

Code: https://gist.github.com/smnorris/b56e8befa55cdabcd92a275bd63e79b5
DEM: https://hillcrestgeo.ca/outgoing/public/dem.tif

thanks

**Comment by smnorris** [comment]
Ok, nevermind - it looks like simply shifting the pour point a few meters fixes things nicely. I'll try burning in streams to avoid this.

**Comment by mdbartos** [comment]
Greetings,

I just wanted to call your attention to the `grid.snap_to_mask` method, which you can use to snap point(s) to the nearest high-accumulation cell. You will need to first compute the accumulation using `grid.accumulation`. See this notebook:
https://github.com/mdbartos/pysheds/blob/master/examples/snap_to_mask.ipynb

**Comment by smnorris** [comment]
Perfect, I missed that one. Thank you.
