### ISSUE TITLE
feature request: transport efficiency in flow accumulation

### ISSUE THREAD

**Issue by itati01** [mdbartos/pysheds#70]
Hi, I propose to slightly extend the flow accumulation to consider transport efficiency, e.g. the effect of reservoirs or riparian buffers. This can be achieved by applying a correction factor between 0 and 1 in `np.add.at() `, e.g. `np.add.at(acc, endnodes, acc[startnodes] * efficiency[startnodes])` in `_d8_accumulation`. Nodata would be replaced by 1 beforehand. The new argument of `accumulation` could either be a ndarray (like weights) or Raster/str (like flow direction). Cheers

**Comment by mdbartos** [comment]
Hi @itati01,

That sounds very interesting. Feel free to submit a pull request if you want to make the change (submit to development branch). Otherwise I can do it within the next week or so.

Thanks,
MDB

**Comment by mdbartos** [comment]
If you do decide to submit a pull request, it would probably be best to create a different case with a separate for-loop, because the additional multiplication will result in a performance hit, even when the `efficiency` array is all ones.

**Comment by itati01** [comment]
Hi @mdbartos ,
I tested D8 with two raster cells having an efficiency of 50 % and it looked fine.

**Comment by mdbartos** [comment]
Resolved in #73
