### ISSUE TITLE
wrong variable name in _set_dirmap

### ISSUE THREAD

**Issue by itati01** [mdbartos/pysheds#74]
Hi @mdbartos,
In _set_dirmap() you refer to an unexisting variable name `direction_name` in `raise KeyError("{0} not found in grid instance".format(direction_name))`. Would it be `data`, instead?

**Comment by mdbartos** [comment]
Yes, that is correct. Thanks for finding these bugs!

**Comment by mdbartos** [comment]
Resolved in #73
