### ISSUE TITLE
incorrect dinf flow accumulation in test_grid.py

### ISSUE THREAD

**Issue by itati01** [mdbartos/pysheds#76]
Hi @mdbartos ,

While working on the test case for transport efficiency (#73), I observed a likely error in the flow accumlation with dinf.

I wanted to place a raster cell with some retention to flow near the outlet of the catchment as defined in test_grid.py. The output of the normal accumulation is attached, with d8 in blue. The reddish cell (A = 8288.15) obviously receives flow from its darkish neighbour (A=11402.86). But what about the remainder? The marked cells have accumulated values <100.
<img width="842" alt="error_dinf_acc_catch" src="https://user-images.githubusercontent.com/20688552/53085040-58f26c80-3502-11e9-9613-8c4f9a6dc87e.png">

**Comment by itati01** [comment]
Another issue: some extra cells appear in top row. I found them while evaluating the flow accumulation with efficiency (#73).

> np.where(grid.dinf_acc_eff<grid.dinf_acc)` 
> Out[92]: (array([0, 0, 3, 4], dtype=int64), array([  4,   5, 131, 132], dtype=int64))

The cells (0,4) and (0,5) are wrong. Without efficiency:
> grid.dinf_acc[0,4]
> Out[94]: 3115.7132796632914
> grid.dinf_acc[0,5]
> Out[95]: 8288.15039690737

Et voilà, they receive the outflow of the darkish cell mentioned above
> grid.dinf_acc[0,5] + grid.dinf_acc[0,4] - grid.dinf_acc.max()
> Out[101]: 1.000000000001819

Which is where I put the retention cell (which matches the observed differences for cells (4,131) and (5,132).

> np.where(grid.dinf_acc==grid.dinf_acc.max())
> Out[106]: (array([3], dtype=int64), array([131], dtype=int64))

The values for (0,5) and (4,132) (the reddish cell above) are identical: 
> grid.dinf_acc[0,5] - grid.dinf_acc[4,132]
> Out[112]: 0.0

<img width="842" alt="spurious_cells_dinf_acc_catch" src="https://user-images.githubusercontent.com/20688552/53086887-41b57e00-3506-11e9-8cdd-8b50152affbd.png">

**Comment by mdbartos** [comment]
Greetings, try updating to pysheds v0.3 and reopen if the issue persists.
