### ISSUE TITLE
The data no longer seems to be available

### ISSUE THREAD

**Issue by tommylees112** [mdbartos/pysheds#82]
The links to the data from the link provided on the `README.md` file no longer work. Is this just a problem for me?

https://hydrosheds.cr.usgs.gov/datadownload.php

## for example
https://earlywarning.usgs.gov/hydrodata/sa_15s_zip_grid/af_dem_15s_grid.zip

![Screenshot 2019-03-25 at 20 38 04](https://user-images.githubusercontent.com/21049064/54952440-e976ff00-4f3d-11e9-8c93-63b8ce7e96f0.png)

**Comment by mdbartos** [comment]
Uh oh. Looks like they might have moved here:
https://hydrosheds.org/downloads

See if that works for you.

**Comment by tommylees112** [comment]
But then the files are too large to allow me to download? Thanks for checking though!

![Screenshot 2019-03-26 at 11 09 56](https://user-images.githubusercontent.com/21049064/54992645-b4a78e00-4fb7-11e9-8ba7-aca798d48d61.png)

**Comment by tommylees112** [comment]
I guess I will have to contact them!

Thanks anyway

**Comment by mdbartos** [comment]
I think you have to go to the next drop-down level:

<img width="559" alt="Screen Shot 2019-03-26 at 1 44 52 PM" src="https://user-images.githubusercontent.com/8175317/55020601-8765da80-4fcd-11e9-9730-9a9c093bc400.png">

**Comment by tommylees112** [comment]
You are very correct! Thankyou
