### ISSUE TITLE
Out of bounds IndexError in catchment method

### ISSUE THREAD

**Issue by DominiqueBrunet** [mdbartos/pysheds#84]
Hi,

While trying to run the no_metadata.ipynb recipe using n30w100_dir data, I got an IndexError because selection is out of bounds. The fix would be to filter selection to make sure that it is within bounds when executing line 925.

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-7-bbe80634b78e> in <module>
      2 catch = grid.catchment(data=fdir, x=x, y=y, dirmap=dirmap, inplace=False,
      3                        recursionlimit=15000, xytype='index', nodata_in=0,
----> 4                        ignore_metadata=True)

pysheds\grid.py in catchment(self, x, y, data, pour_value, out_name, dirmap, nodata_in, nodata_out, xytype, routing, recursionlimit, inplace, apply_mask, ignore_metadata, **kwargs)
    900                                       xytype=xytype, recursionlimit=recursionlimit, inplace=inplace,
    901                                       apply_mask=apply_mask, ignore_metadata=ignore_metadata,
--> 902                                       properties=properties, metadata=metadata, **kwargs)
    903         elif routing.lower() == 'dinf':
    904             return self._dinf_catchment(x, y, fdir=fdir, pour_value=pour_value, out_name=out_name,

pysheds\grid.py in _d8_catchment(self, x, y, fdir, pour_value, out_name, dirmap, nodata_in, nodata_out, xytype, recursionlimit, inplace, apply_mask, ignore_metadata, properties, metadata, **kwargs)
    945             # call catchment search starting at the pour point
    946             collect = []
--> 947             d8_catchment_search(pour_point)
    948             # initialize output array
    949             outcatch = np.zeros(fdir.shape, dtype=int)

pysheds\grid.py in d8_catchment_search(cells)
    923             selection = self._select_surround_ravel(cells, fdir.shape)
    924             # TODO: Why use np.where here?
--> 925             next_idx = selection[(fdir.flat[selection] == r_dirmap)]
    926             if next_idx.any():
    927                 return d8_catchment_search(next_idx)

IndexError: index 36004698 is out of bounds for size 36000000
------------------------------------------------------------------------------------

**Comment by mdbartos** [comment]
Hi @DominiqueBrunet,

I'll take a look at this as soon as I get a chance. Usually an out of bounds error occurs when the wrong xytype argument is given, or the edge cells are not properly masked.

It's possible that removing the ignore_metadata argument could fix the problem in this case. This notebook is somewhat dated, and some breaking changes related to ignore_metadata may have occurred in the meantime.

**Comment by mdbartos** [comment]
Greetings, this should be fixed in pysheds v0.3. Please reopen an issue if the problem persists.
