### ISSUE TITLE
Can i read in a direction grid instead of going through the dem method?

### ISSUE THREAD

**Issue by tommylees112** [mdbartos/pysheds#85]
I want to calculate the upstream area contributing to streamflow at a pour point. 

Can I skip reading in the `dem` and read the direction `.adf` file directly from Hydrosheds? This seems to be one big file for all of Africa as opposed to the many sub-directories for the DEM file.

# the directory for the direction
```
├── af_dir_15s
│   ├── af_dir_15s
│   │   ├── dblbnd.adf
│   │   ├── hdr.adf
│   │   ├── metadata.htm
│   │   ├── metadata.xml
│   │   ├── prj.adf
│   │   ├── sta.adf
│   │   ├── vat.adf
│   │   ├── w001001.adf
│   │   └── w001001x.adf
│   └── info
│       ├── arc0000.dat
│       ├── arc0000.nit
│       ├── arc0001.dat
│       ├── arc0001.nit
│       ├── arc0002.dat
│       ├── arc0002.nit
│       ├── arc0002r.001
│       └── arc.dir
├── af_dir_15s_grid.zip
├── hydrosheds-275331d1883b03c7ce4f.zip
└── HydroSHEDS_TechDoc_v10.pdf
```

# the dem directory
```
── s35e025_con
│   ├── info
│   │   ├── arc0000.dat
│   │   ├── arc0000.nit
│   │   ├── arc0001.dat
│   │   ├── arc0001.nit
│   │   ├── arc0002.dat
│   │   ├── arc0002.nit
│   │   ├── arc0002r.001
│   │   └── arc.dir
│   └── s35e025_con
│       ├── dblbnd.adf
│       ├── hdr.adf
│       ├── metadata.htm
│       ├── metadata.xml
│       ├── prj.adf
│       ├── sta.adf
│       ├── vat.adf
│       ├── w001001.adf
│       └── w001001x.adf
├── s35e025_con_grid.zip
├── s35e030_con
│   ├── info
│   │   ├── arc0000.dat
│   │   ├── arc0000.nit
│   │   ├── arc0001.dat
│   │   ├── arc0001.nit
│   │   ├── arc0002.dat
│   │   ├── arc0002.nit
│   │   ├── arc0002r.001
│   │   └── arc.dir
│   └── s35e030_con
│       ├── dblbnd.adf
│       ├── hdr.adf
│       ├── metadata.htm
│       ├── metadata.xml
│       ├── prj.adf
│       ├── sta.adf
│       ├── vat.adf
│       ├── w001001.adf
│       └── w001001x.adf
├── s35e030_con_grid.zip
```
The reason being that I have never worked with` .adf` files before and there are lots of them in the DEM for Africa, but I only want a small region of East Africa and it is not entirely clear to me which file corresponds to my region of interest.

Otherwise is there a way in pysheds of opening all the .adf folders and merging the .adf files together into one shapefile?

I know very specific, what I am trying to do is delineate the area of a catchment for stations, so I can a) look at the upstream precipitation and evaporation, b) can normalise the flow by the area of the contributing catchment.

Thanks for any help/advice! very much appreciated

**Comment by emiliom** [comment]
I'm new to pysheds, but it uses `rasterio` to read rasters. rasterio supports reading the ESRI grids you're referring, where the data are found in a folder.

You can definitely work directly with the flow direction grid, w/o the DEM. You can see an example in cell 3 at https://github.com/mdbartos/pysheds/blob/master/examples/shapefiles.ipynb

In the HydroSHEDS 15s data you're using, the entire continent is one grid (it's not tiled). In rasterio you point to the `hdr.adf` file path to read the grid. So, for your Africa grid, I assume it'd look like this:

```python
grid = Grid.from_raster("af_dir_15s/af_dir_15s/hdr.adf", data_name='dir')
```

**Comment by mdbartos** [comment]
The above answer is correct. Note that datasets as named attributes of `Grid` instances have been removed in v0.3.

**Comment by rheinheimer** [comment]
Greetings @mdbartos,  The above Jupyter example shows the catchment being calculated without specifying the fdir as an argument. However, not including fdir appears to throw an exception.
```python
    grid = Grid.from_raster('./data/hyd_na_dir_30s.tif', data_name='dir')
    dirmap = (64, 128, 1, 2, 4, 8, 16, 32)
    catchment = grid.catchment(x=x, y=y, data='dir', dirmap=dirmap, xytype='coordinate')
```
Should this still work?  Thanks!
