### ISSUE TITLE
RasterioIOError

### ISSUE THREAD

**Issue by lapyrodas** [mdbartos/pysheds#86]
Hi, when I try to run  `Grid.from_raster('C:\pysheds\data', data_name='dem')` I receive the following error `RasterioIOError: C:\pysheds\data: Permission denied`, What can I do in this case??

**Comment by mdbartos** [comment]
My guess would be that the user you are running python as don't have permission to access that directory. Copy the data somewhere you have access to (e.g. your home directory, Documents, etc.).

**Comment by mdbartos** [comment]
Please reopen if this issue persists.
