### ISSUE TITLE
Turn grid into .shp file?

### ISSUE THREAD

**Issue by PierreRCM** [mdbartos/pysheds#87]
Hey !

I was wondering if it was possible to turn my grid instance into a shape file ".shp". I'm reading a .tif, and trying to get the contribution of the watershed for a certain x,y position, then save the contribution watershed to a .shp. 

Thanks for help :)

**Comment by mdbartos** [comment]
Hi Pierre,

Sure you can do that. I have a notebook with code here: https://github.com/mdbartos/pysheds/blob/master/recipes/write_shapefile.ipynb

More documentation is here:
https://mdbartos.github.io/pysheds/file-io.html

Let me know if you have any questions.

Thanks,
MDB

**Comment by PierreRCM** [comment]
Thanks a lot.
