### ISSUE TITLE
Issue with Catchment

### ISSUE THREAD

**Issue by ayebiahwea** [mdbartos/pysheds#89]
Hello,

I am using a Ghana TIFF(attached) to perform the Rapid Flood Spilling Model for a final class project. However, I get an error whenever I specify any pour points to delineate catchment from the flow direction. 

Can you please help to get over this step? The error that I get is below as well.
![image](https://user-images.githubusercontent.com/29642264/57482935-e6c53480-7273-11e9-91a1-1dae772df79c.png)

Below is the folder with the python code and the Ghana Tiff file
[Elevation.zip](https://github.com/mdbartos/pysheds/files/3163778/Elevation.zip)

Thanks,
Anthony.

**Comment by mdbartos** [comment]
Make sure that the 'blockxsize' is argument is less than the horizontal dimensions of the raster. Similarly, 'blockysize' has to be less than the vertical dimensions of your raster. So for instance, try setting blockxsize to 16.

See also:
https://github.com/mdbartos/pysheds/issues/60

**Comment by mdbartos** [comment]
Please reopen if the issue persists.
