### ISSUE TITLE
d8 accumulation: issue with acc[0] = 1

### ISSUE THREAD

**Issue by itati01** [mdbartos/pysheds#92]
Hi,

I tested the D8 flow accumulation with a weight grid (1|0) and observed that  ```acc[0] = 1``` is wrong. The intermediate results show correctly ```acc[0] == 0```. Why is this "hacky fix" (according to your comment) needed?

**Comment by mdbartos** [comment]
Greetings,

I believe it's because 0 is used as the 'throw-away' index when running the accumulation loop. I would need to check if this is still the case though.

In any case, one could simply set the accumulation at that cell to the sum of the directed accumulations around it.

**Comment by itati01** [comment]
While preparing the example below, I found another issue regarding the padding. But first things first. 

At the first glance, ```acc[0]=1``` should be replaced by something like
```
if weights is None:
    acc[0] = 1
else:
    acc[0] = weights[0]
```
Otherwise results are unexpected when weight values != 1are used:
```
import numpy as np
# we need affine transformation and projection below which we can borrow from any reference raster
ref = "path_to_ref_raster"
grid = Grid()
grid.read_raster(ref, "test")

# create raster with flow directions
# flow cumulates in columns 0-2, from S -> N
fdir = np.array([(64,64,64,16,16),(64,64,64,16,16),(64,64,64,16,16),(64,64,64,16,16),(64,64,64,16,16)])
grid1 = Grid()
grid1.add_gridded_data(fdir, "fdir", affine=grid.affine, crs=grid.crs, nodata=-9999)
# weight is 2 for all cells, same shape as flow direction
weight = np.ones_like(fdir) * 2
# expected: acc[0] == 2, but is set to 1
grid1.accumulation("fdir", weights=weight, out_name="acc", dirmap=(64,128,1,2,4,8,16,32), routing="d8")
print(grid1.acc)
```

But actually, the assignment seems to be unnecessary. The fix above would now set (0,0) to the weight of 1, so we still get 1 but it should also contain the modified flow from column 1. I got plausible values after commenting out the line.
```
# changed 2nd tuple = index 1,1
fdir = np.array([(64,64,64,16,16),(64,32,64,16,16),(64,64,64,16,16),(64,64,64,16,16),(64,64,64,16,16)])
# we use weights of 1
weight = np.ones_like(fdir)
grid1 = Grid()
grid1.add_gridded_data(fdir, "fdir", affine=grid.affine, crs=grid.crs, nodata=-9999)
grid1.accumulation("fdir", weights=weight, out_name="acc", dirmap=(64,128,1,2,4,8,16,32), routing="d8")
print(grid1.acc)
```

Regarding the padding issue:

With ```pad=True```, this acc[0]=1 is not revelant and the script would work as intended - without the weight array. Due to the padding, the size of the weight (and a efficiency) raster is not matching anymore (Assertion error). So, weights and efficiency arrays should also be padded at the very beginning. Just try
```grid1.accumulation("fdir", weights=weight, out_name="acc", dirmap=(64,128,1,2,4,8,16,32), routing="d8", pad=True)```. 

What do you think about having pad=True as default in the flow accumulation? Without padding, the current default output might be surprising for some users. However, in real-world applications we might have a "safety margin" anyway to avoid boundary effects. So, this should be no common issue.

**Comment by mdbartos** [comment]
Hi @itati01 

Apologies! I forgot about this thread 🙏

I think I originally had it as pad=True by default, but changed it after noticing that most other libraries did it the other way. Having pad=False ultimately seemed more "correct", given that it's impossible to know what the boundary cells should be without outside information.

Let me know if you have any fixes that you'd like to submit a PR for.

**Comment by mdbartos** [comment]
This issue should be fixed, as `accumulation` was reimplemented in numba for pysheds v0.3.
