### ISSUE TITLE
Calculate HAND fast with Numba

### ISSUE THREAD

**Issue by j08lue** [mdbartos/pysheds#93]
I can see PySheds has an [implementation](https://github.com/mdbartos/pysheds/blob/8e3c8da46ec6475b1fea64647f017ed073ea5bf6/pysheds/grid.py#L1689) of HAND that could use a bit of care (judging from the `TODO`s and `try ... except`s...). While I unfortunately can't provide that care right now, a colleague a while back made a neat implementation using Numba that I am happy to share if it can be used here. https://gist.github.com/j08lue/04c8df062e54390fbc704187a497da14 It is set up to use flow dir and stream network computed with GRASS GIS, but can probably easily be adapted. What do you think?

**Comment by mdbartos** [comment]
Hi @j08lue, looks cool! I've been interested in applying numba to pysheds myself (to ensure portability, it might be best to make it an optional dependency though). It would be interesting to see   how the performance compares.

**Comment by j08lue** [comment]
> to ensure portability, it might be best to make it an optional dependency though

Well, if someone is able to install your current dependencies, you can be pretty sure they can also do numba. 😄

https://github.com/mdbartos/pysheds/blob/f1d8d3f19a760de36077f3fb093d7a4e3a5550db/setup.py#L13-L21

**Comment by mdbartos** [comment]
Addressed in #143
