### ISSUE TITLE
wrong gridsize (use shape + 1  as denominator in _dy_dx)

### ISSUE THREAD

**Issue by itati01** [mdbartos/pysheds#96]
Hi,

is the bbox / extent correctly defined? I have a grid, for which QGIS gives me:

Extent: 354980, 5721600, 414110, 5760970
Cell size 5,-5

and pysheds:
grid.bbox: 354980, 5721595, 414115, 5760970
grid.cellsize: 5.00053

xmin and ymax are identical, while ymin is 1 cell lower and xmax 1 cell larger. This results in a wrong grid.cellsize. 

So, to answer your questions in the comments below: it's ```(shape +1)```, if the bbox is needed in this way (or use grid.affine).
``` 
dy = np.abs(y1 - y0) / (self.shape[0]) #TODO: Should this be shape - 1?
dx = np.abs(x1 - x0) / (self.shape[1]) #TODO: Should this be shape - 1?
```

**Comment by mdbartos** [comment]
Hi @itati01 

Great find. It would probably be best to have a robust unit test for this. Let me know if you'd like to look into it.

**Comment by mdbartos** [comment]
Greetings, _dy_dx is now redefined in terms of the affine transformation matrix, which should fix this issue.
