### ISSUE TITLE
Problem with loading DEM as numpy array

### ISSUE THREAD

**Issue by LucaFab** [mdbartos/pysheds#99]
After loading a DEM model directly as a raw numpy array, I am attempting to go through the usual steps (visualization, catchment computation, etc.).  For instance, by loading a randomly created DEM model (example taken from documentation)

`grid = Grid()`
`data = np.random.randn(100,100)`
`grid.add_gridded_data(data=data, data_name='random',
                          affine=grid.affine,
                          crs=grid.crs,
                          nodata=0)
grid.view('random')`

However, already when trying to visualize the data, I am encountering the following exception error:

`---------------------------------------------------------------------------
TransformNotInvertibleError               Traceback (most recent call last)
<ipython-input-49-6b51eb9ce262> in <module>
      3                          crs=grid.crs,
      4                          nodata=0)
----> 5 grid.view('random')

C:\ProgramData\Anaconda3\lib\site-packages\pysheds\grid.py in view(self, data, data_view, target_view, apply_mask, nodata, interpolation, as_crs, return_coords, kx, ky, s, tolerance, dtype, metadata)
    454             # If doing nearest neighbor search, use fast sorted search
    455             if interpolation == 'nearest':
--> 456                 array_view = RegularGridViewer._view_affine(data, data_view, target_view)
    457             # If spline interpolation is needed, use RectBivariate
    458             elif interpolation == 'spline':

C:\ProgramData\Anaconda3\lib\site-packages\pysheds\view.py in _view_affine(cls, data, data_view, target_view, x_tolerance, y_tolerance)
    294         view = np.full(target_view.shape, nodata, dtype=data.dtype)
    295         viewrows, viewcols = target_view.grid_indices()
--> 296         _, target_row_ix = ~data_view.affine * np.vstack([np.zeros(target_view.shape[0]), viewrows])
    297         target_col_ix, _ = ~data_view.affine * np.vstack([viewcols, np.zeros(target_view.shape[1])])
    298         y_ix = np.around(target_row_ix).astype(int)

C:\ProgramData\Anaconda3\lib\site-packages\affine\__init__.py in __invert__(self)
    549         if self.is_degenerate:
    550             raise TransformNotInvertibleError(
--> 551                 "Cannot invert degenerate transform")
    552         idet = 1.0 / self.determinant
    553         sa, sb, sc, sd, se, sf, _, _, _ = self

TransformNotInvertibleError: Cannot invert degenerate transform`

**Comment by nil-is-lin** [comment]
I have also encountered this problem

**Comment by mdbartos** [comment]
The problem here is that the default affine transform is set to (0,0,0,0,0,0), meaning that the assumed pixel width and height are set to 0. If there is no affine information available, you can get around this problem by assuming a pixel/width height of 1. So, for example:

```python
import numpy as np
from affine import Affine
from scipy.ndimage import gaussian_filter
import matplotlib.pyplot as plt
from pysheds.grid import Grid

# Create fake DEM with some depressions ranging from
# 10 meters in elevation to 0 meters
np.random.seed(100)
raw = np.random.uniform(size=[200,200])*10
dem = gaussian_filter(raw,sigma=8)

affine = Affine(1,0,0,0,1,0)
grid = Grid()
grid.add_gridded_data(dem,'dem',affine=affine,
                     crs={'init':'epsg:32614'})
dem_view  = grid.view('dem',apply_mask=False)
```

(From: #94)

I can change the default so that it will work for an empty grid. If you are loading real data though, this problem shouldn't occur.

**Comment by nil-is-lin** [comment]
OK, it works for me. Many THX.

**Comment by mdbartos** [comment]
Default affine transformation has been set to nonsingular in pysheds v0.3.
